// <auto-generated />
namespace ControleEquipamentos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Inicio1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inicio1));
        
        string IMigrationMetadata.Id
        {
            get { return "201910011819472_Inicio1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
