// <auto-generated />
namespace ControleEquipamentos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Alteracao0101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alteracao0101));
        
        string IMigrationMetadata.Id
        {
            get { return "201909302239038_Alteracao0101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
