// <auto-generated />
namespace ControleEquipamentos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class alteracao0401 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteracao0401));
        
        string IMigrationMetadata.Id
        {
            get { return "201910032332322_alteracao0401"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
